apiVersion: v1
kind: Service
metadata:
  name: customer-manager-api
spec:
  selector:
    app: customer-manager-api
  ports:
    - port: 80
      targetPort: 9000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-manager-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-manager-api
  template:
    metadata:
      labels:
        app: customer-manager-api
    spec:
      containers:
        - name: customer-manager-api
          image: anushasankaranarayanan/customer-manager-api:1.0.0
          ports:
            - containerPort: 9000
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/customer_db
          imagePullPolicy: Always